PROG=	smtpsend
SRCS=	smtpsend.c
        
CFLAGS+= -O2 -Wall -pipe
LDFLAGS+= -pthread
YFLAGS=
MAN=	smtpsend.8
MANDIR = /usr/local/man/cat
BINDIR = /usr/local/sbin
BINOWN  =       root
BINMODE =       0555

.include <bsd.prog.mk>
